# Generated by Django 3.2.20 on 2023-07-26 08:38
# pylint:disable = C0103, C0114
# noqa: E265
from django.db import migrations, models


class Migration(migrations.Migration):
    "Migration"

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
